import type { CSSProperties, HTMLAttributes } from 'react'
import {
  Activity,
  AlertTriangle,
  Antenna,
  ArrowLeftRight,
  ArrowRight,
  ArrowUpCircle,
  Atom,
  Award,
  BadgeCheck,
  BarChart3,
  Bell,
  BellOff,
  Biohazard,
  Bird,
  Bot,
  Box,
  Brain,
  Briefcase,
  Bug,
  Calendar,
  CalendarClock,
  Check,
  CheckCheck,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsUp,
  CircleDashed,
  Clock,
  Coffee,
  Coins,
  Copy,
  CornerDownLeft,
  Cpu,
  Crosshair,
  Crown,
  Database,
  Download,
  Drama,
  Dumbbell,
  Filter,
  Flag,
  FlagTriangleRight,
  Flame,
  Gauge,
  GaugeCircle,
  Gem,
  Ghost,
  Gift,
  GitBranch,
  Hammer,
  HelpCircle,
  Hourglass,
  Info,
  KeyRound,
  Landmark,
  LayoutDashboard,
  LayoutGrid,
  ListChecks,
  Lock,
  type LucideIcon,
  Milestone,
  Minus,
  MousePointerClick,
  Orbit,
  Package,
  PackageOpen,
  Palette,
  Pencil,
  Pin,
  Play,
  Plus,
  Radar,
  Radio,
  RadioTower,
  Repeat,
  RotateCcw,
  Save,
  ScanSearch,
  ScrollText,
  Server,
  Share2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShieldX,
  Shirt,
  Skull,
  Snowflake,
  Sparkles,
  Split,
  SquarePen,
  Terminal,
  Timer,
  Trash2,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Trophy,
  Undo2,
  Unlock,
  User,
  UserRound,
  Waves,
  X,
  XCircle,
  Zap,
  ZapOff,
} from 'lucide-react'

/**
 * Registre statique des icônes Lucide réellement utilisées par l'application.
 *
 * On n'utilise volontairement PAS le chargement dynamique de lucide-react :
 * il éclate les ~1600 icônes en autant de chunks, tous précachés par la PWA
 * (~2,2 Mo). Le registre statique est tree-shaké → bundle léger, précache
 * réduit, fonctionnement hors-ligne garanti.
 *
 * Pour ajouter une icône : l'importer ci-dessus et l'enregistrer ici sous son
 * nom kebab-case (celui exposé par l'API `name` du composant Icon).
 */
const REGISTRY: Record<string, LucideIcon> = {
  activity: Activity,
  'alert-triangle': AlertTriangle,
  antenna: Antenna,
  'arrow-left-right': ArrowLeftRight,
  'arrow-right': ArrowRight,
  'arrow-up-circle': ArrowUpCircle,
  atom: Atom,
  award: Award,
  'badge-check': BadgeCheck,
  'bar-chart-3': BarChart3,
  bell: Bell,
  'bell-off': BellOff,
  biohazard: Biohazard,
  bird: Bird,
  bot: Bot,
  box: Box,
  brain: Brain,
  briefcase: Briefcase,
  bug: Bug,
  calendar: Calendar,
  'calendar-clock': CalendarClock,
  check: Check,
  'check-check': CheckCheck,
  'check-circle': CheckCircle,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevrons-up': ChevronsUp,
  'circle-dashed': CircleDashed,
  clock: Clock,
  coffee: Coffee,
  coins: Coins,
  copy: Copy,
  'corner-down-left': CornerDownLeft,
  cpu: Cpu,
  crosshair: Crosshair,
  crown: Crown,
  database: Database,
  download: Download,
  drama: Drama,
  dumbbell: Dumbbell,
  filter: Filter,
  flag: Flag,
  'flag-triangle-right': FlagTriangleRight,
  flame: Flame,
  gauge: Gauge,
  'gauge-circle': GaugeCircle,
  gem: Gem,
  ghost: Ghost,
  gift: Gift,
  'git-branch': GitBranch,
  hammer: Hammer,
  'help-circle': HelpCircle,
  hourglass: Hourglass,
  info: Info,
  'key-round': KeyRound,
  landmark: Landmark,
  'layout-dashboard': LayoutDashboard,
  'layout-grid': LayoutGrid,
  'list-checks': ListChecks,
  lock: Lock,
  milestone: Milestone,
  minus: Minus,
  'mouse-pointer-click': MousePointerClick,
  orbit: Orbit,
  package: Package,
  'package-open': PackageOpen,
  palette: Palette,
  pencil: Pencil,
  pin: Pin,
  play: Play,
  plus: Plus,
  radar: Radar,
  radio: Radio,
  'radio-tower': RadioTower,
  repeat: Repeat,
  'rotate-ccw': RotateCcw,
  save: Save,
  'scan-search': ScanSearch,
  'scroll-text': ScrollText,
  server: Server,
  'share-2': Share2,
  shield: Shield,
  'shield-alert': ShieldAlert,
  'shield-check': ShieldCheck,
  'shield-x': ShieldX,
  shirt: Shirt,
  skull: Skull,
  snowflake: Snowflake,
  sparkles: Sparkles,
  split: Split,
  'square-pen': SquarePen,
  terminal: Terminal,
  timer: Timer,
  'trash-2': Trash2,
  'trending-down': TrendingDown,
  'trending-up': TrendingUp,
  'triangle-alert': TriangleAlert,
  trophy: Trophy,
  'undo-2': Undo2,
  unlock: Unlock,
  user: User,
  'user-round': UserRound,
  waves: Waves,
  x: X,
  'x-circle': XCircle,
  zap: Zap,
  'zap-off': ZapOff,
}

export interface IconProps {
  /** Nom d'icône Lucide en kebab-case (ex. "zap", "shield-alert"). */
  name: string
  /** Taille en pixels. @default 18 */
  size?: number
  /** @default 2 */
  strokeWidth?: number
  /** @default "currentColor" */
  color?: string
  style?: CSSProperties
}

/**
 * Icône ligne du set Lucide (iconographie fine du design system NIGHTWIRE).
 * Portée sur `lucide-react` (chargement local, hors-ligne) au lieu du CDN
 * d'origine ; l'API `name` en kebab-case est conservée. Un nom absent du
 * registre ne rend rien (pas d'erreur).
 */
export function Icon({
  name,
  size = 18,
  strokeWidth = 2,
  color = 'currentColor',
  style = {},
  ...rest
}: IconProps & Omit<HTMLAttributes<HTMLSpanElement>, keyof IconProps>) {
  const Glyph = REGISTRY[name]
  return (
    <span
      aria-hidden="true"
      style={{ display: 'inline-flex', color, lineHeight: 0, ...style }}
      {...rest}
    >
      {Glyph && <Glyph size={size} strokeWidth={strokeWidth} />}
    </span>
  )
}
